config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :feeds
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only:[:create, :destroy, :index]
  #mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds
  has_many :favorites, dependent: :destroy
  has_many :favorite_feeds, through: :favorites, source: :feed 

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り解除しました"
  end

  def index
    @favorite_feeds = current_user.favorite_feeds
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    respond_to do |format|
      if @feed.save
      #ConfirmationMailer.confirmation_mail(current_user).deliver
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to feeds_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
   session.delete(:user_id)
   flash[:notice] = 'ログアウトしました'
   redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>

<% @favorite_feeds.each do |feed| %>
  <tr>
    <td>
      <h5>投稿者：<%= feed.user.name %></h5>
      <%= image_tag feed.image,size:150 %>
    </td>
      <%#= feed.image %>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :feed_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed, class: 'btn btn-success btn-sm' %> |
<%= link_to 'Back', feeds_path, class: 'btn btn-success btn-sm' %>

app/views/feeds/index.html.erb
<!--<p id="notice"><%= notice %></p>!-->

<h1>Instakun</h1>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td>
          <h5>投稿者：<%= feed.user.name %></h5>
          <%= image_tag feed.image,size:150 %>
        </td>
          <%#= feed.image %>
        <td>・<%= link_to 'Show', feed, class: 'btn btn-success btn-sm' %></td>
        <td>・<%= link_to 'Edit', edit_feed_path(feed), class: 'btn btn-success btn-sm' %></td>
        <td>・<%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

・<%= link_to '新規投稿', new_feed_path, class: 'btn btn-success btn-sm' %>

app/views/feeds/new.html.erb
<h1>let's toukou!</h1>

<%= render 'form', feed: @feed, class: 'btn btn-success btn-sm' %>

<%= link_to 'Back', feeds_path, class: 'btn btn-success btn-sm' %>

app/views/feeds/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image %>
</p>
<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>
<% if @feed.user_id != current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-success btn-sm' %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_feed_path(@feed), class: 'btn btn-success btn-sm' %> |
<%= link_to 'Back', feeds_path, class: 'btn btn-success btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <div class="container-fluid">
      <head>
        <title>Instakun</title>
        <p>写真にコメントを添えて投稿しよう！</p>
          <%= csrf_meta_tags %>
          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
      <body>
        <nav class="menu">
          <ul class="row">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
            <% end %>
        <nav class="menu">
          <ul class="row">
            <% if logged_in? %>

              <li class="col-sm-6"><%= link_to "Profile", user_path(current_user.id), class: 'btn btn-success btn-sm' %></li>

              <li class="col-sm-6"><%= link_to "投稿一覧", feeds_path, class: 'btn btn-success btn-sm' %></li>

              <li class="col-sm-6"><%= link_to "お気に入り一覧", favorites_path, class: 'btn btn-success btn-sm' %></li>

              <li class="col-sm-6"><%= link_to "Logout", session_path(current_user.id), method: :delete, class: 'btn btn-success btn-sm' %></li>

            <% else %>
              <li class="col-sm-6"><%= link_to "Sign up", new_user_path, class: 'btn btn-success btn-sm' %></li>
              <li class="col-sm-6"><%= link_to "Login", new_session_path, class: 'btn btn-success btn-sm' %></li>

            <% end %>
            <%= yield %>
          </ul>
        </nav>
      </body>
    </div>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<h2>Sighn up後はLog inをしてください</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>